### ISSUE TITLE
Please stop.

### ISSUE THREAD

**Issue by mcmonkey4eva** [Jabelpeeps/Sentries#5]
It is ridiculously inappropriate to spam other plugins with advertisements to your own.

Please, cease and desist.

**Comment by mcmonkey4eva** [comment]
Referring, of course, to this: http://puu.sh/stB5P.png

**Comment by PsychoLynx** [comment]
@Jabelpeeps  Furthermore, are there even any indications that your plugin integrates with War? If not, I have zero interest in switching.

**Comment by Jabelpeeps** [comment]
@PsychoLynx Here is a link to the class file that manages the War integration:-
https://github.com/Jabelpeeps/Sentries/blob/master/src/org/jabelpeeps/sentries/pluginbridges/WarBridge.java
One of my goals when setting out on this project was to retain all the current functions of Sentry through the refactoring phase, before adding new ones.  This included the plugin integrations, which although not exactly the same - in terms of configuring them - should allow Sentries to select targets to attack on the basis of this.
Having said that, I have zero experience of running the War plugin from an server admin perspective, and so I have been unable to test that the functionality will behave in-game in the way that you might want it to.  However if you run into problems, let me know, and I'll look into fixing them as soon as I can.

**Comment by Jabelpeeps** [comment]
@mcmonkey4eva 

I will do so, if you will agree to stop referring to Sentry/Sentries as abandoned/finished/deprecated. 

You know perfectly well that I was continuing to work on my fork, as I informed you in a PR from the outset, and several times thereafter.  

Now that I am trying to spread awareness of this fact to players that you have misled, I find this rather rich to be honest.

**Comment by mcmonkey4eva** [comment]
@Jabelpeeps as you have no connection to the Citizens team (you're not even in our IRC anymore?!) you continuing Sentry is unauthorized, unofficial, and due to there being an official replacement, generally annoying at best.

**Comment by Jabelpeeps** [comment]
@mcmonkey4eva 
Since when was a "connection with the Citizens team", or authorisation required to use the Citizens API?  I think you may have over-stepped your mark there.

I'm sure you've heard of the concept of open source projects being forked when developers want to go in different directions, and I really can't see what I am doing wrong here.  All I am doing is continuing to work on a project that you no-longer have any interest in.  I don't see how that gives you the right to denigrate me or my work, making claims that you can't substantiate about it.

**Comment by mcmonkey4eva** [comment]
Your edits to the title show your disturbing lack of care for player choice.

**Comment by Jabelpeeps** [comment]
Please explain.

**Comment by mcmonkey4eva** [comment]
Anyway, you're reworking entirely a project that existed within a team as a public service. And then you're putting it out as your own thing, outside the team.
FURTHER, you said we no longer had interest in it: that's wrong. The Citizens team remains interested in it, thus why we took the time to restart the project under a new banner with a better system.
You taking the broken old system and proudly declaring it your choice makes no sense.
With that attitude, why develop for Spigot? Spigot is the replacement for Bukkit which was the replacement for hMod. Let's all go develop for hMod. _Because the original is better than a rewrite, right?_

**Comment by Jabelpeeps** [comment]
I have never tried to put this out as my "own thing", if you read the Sentries readme, I have credited the former authors, and thanked them.

I maintain that you are not interested in Sentry/Sentries, which is why you started with Sentinel.  If you were interested in Sentry, you would still be working on it.  It seems you are interested in working on a combat NPC plugin, and good luck to you, but your claiming any interest in Sentry just appears to be deliberate obfuscation.

Whilst I understand that it can sometimes be a better decision to start again on a project if it is irretrievably broken, and that this is what you decided to do, I felt differently.  I still don't see why you are so offended by this.  Yes I made a choice, yes it is different to yours, can we not co-exist peacefully?

We have a difference of opinion, that stops us being able to work together, as we also did when we were working on dSentry together.   If we end up with two NPC combat plugins that use the Citizens API, does it really matter that much?  The Bukkit/Spigot ecosphere is full of plugins that do similar things;  how many perms plugins are there? or economy plugins? or chat plugins?  None of them take anything away from the others, and between them they all allow server operators the choice to pick the one that offers them the features that they want to use.

mcmonkey4eva said:-
"Your edits to the title show your disturbing lack of care for player choice."

I was actually asking for an explanation for this, as from where I am sitting, it looks as though it is you that is limiting choice, not I.

**Comment by mcmonkey4eva** [comment]
I'm done with this pointless argument.

You're clearly not going to be contributing upstream, and as such, we (the Citizens team) will not be in any way supporting your efforts. We may even actively discourage usage of them if pressed.

**Comment by Jabelpeeps** [comment]
I take it you're done with the argument, as you have no good replies to my points.

I have never asked you or any of the Citizens Team to support me or my efforts.

I have just asked you, @mcmonkey4eva, to stop discouraging people from trying alternatives.  

If, as you claim, Sentinel is so much better, you have nothing to worry about.  

I don't see how I can contribute upstream, when our code bases are so different, and we don't seem to be able to work together peacefully.

**Comment by mcmonkey4eva** [comment]
I asked you not to spam my repo, that was my only intent in coming here.

You could easily contribute upstream by accepting that Sentinel is a better set of base code than Sentry ever was, and work from there.

And I will happily discourage people from trying a lower quality alternative to a higher quality official product. You can't stop me from doing that, just as I can't stop you from doing this waste of time, apparently!

**Comment by Jabelpeeps** [comment]
And I ask you again... on what are you judging the quality of my "product"?

And again... Why can't we co-exist peacefully?

**Comment by Jabelpeeps** [comment]
no answers?

**Comment by enterih** [comment]
I have a question! Why Sentry will stop working? Why u have started Sentinel @mcmonkey4eva
